name: GitHub Action Linting
on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: actionlint
        uses: raven-actions/actionlint@v2
        env:
          SHELLCHECK_OPTS: --exclude=SC2086
