name: GitHub Action Linting
on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2
        env:
          SHELLCHECK_OPTS: --exclude=SC2086
