name: Commit-lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    if: github.base_ref == github.ref || !contains(fromJson('["prettier-code", "renovate/"]'),github.head_ref)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: wagoid/commitlint-github-action@v6
